adminset/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cmdb/', include('cmdb.urls')),
    url(r'^navi/', include('navi.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('setup.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^appconf/', include('appconf.urls')),
    url(r'^delivery/', include('delivery.urls')),
]

appconf/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
import product, project, appowner, authinfo

urlpatterns = [
    url(r'^$', product.product_list, name='appconf'),
    url(r'^appowner/add/$', appowner.appowner_add, name='appowner_add'),
    url(r'^appowner/add/mini/$', appowner.appowner_add_mini, name='appowner_add_mini'),
    url(r'^appowner/list/$', appowner.appowner_list, name='appowner_list'),
    url(r'^appowner/edit/(?P<appowner_id>\d+)/$', appowner.appowner_edit, name='appowner_edit'),
    url(r'^appowner/delete/$', appowner.appowner_del, name='appowner_del'),
    url(r'^product/add/$', product.product_add, name='product_add'),
    url(r'^product/list/$', product.product_list, name='product_list'),
    url(r'^product/project_list/(?P<product_id>\d+)/$', product.project_list, name='product_project_list'),
    url(r'^product/edit/(?P<product_id>\d+)/$', product.product_edit, name='product_edit'),
    url(r'^product/delete/$', product.product_del, name='product_del'),
    url(r'^project/add/$', project.project_add, name='project_add'),
    url(r'^project/list/$', project.project_list, name='project_list'),
    url(r'^project/edit/(?P<project_id>\d+)/$', project.project_edit, name='project_edit'),
    url(r'^project/delete/$', project.project_del, name='project_del'),
    url(r'^project/export/$', project.project_export, name='project_export'),
    url(r'^authinfo/add/$', authinfo.authinfo_add, name='authinfo_add'),
    url(r'^authinfo/add/mini/$', authinfo.authinfo_add_mini, name='authinfo_add_mini'),
    url(r'^authinfo/list/$', authinfo.authinfo_list, name='authinfo_list'),
    url(r'^authinfo/edit/(?P<authinfo_id>\d+)/$', authinfo.authinfo_edit, name='authinfo_edit'),
    url(r'^authinfo/delete/$', authinfo.authinfo_del, name='authinfo_del'),
]

cmdb/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from cmdb import api, idc, asset, group, cabinet


urlpatterns = [
    url(r'asset/$', asset.asset, name='cmdb'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_del, name='asset_del'),
    url(r'^asset/edit/(?P<ids>\d+)/$', asset.asset_edit, name='asset_edit'),
    url(r'^asset/detail/(?P<ids>\d+)/$', asset.server_detail, name='server_detail'),
    # url(r'^asset/save/$', asset.asset_save, name='asset_save'),
    url(r'^group/$', group.group, name='group'),
    url(r'^group/del/$', group.group_del, name='group_del'),
    url(r'^group/add/$', group.group_add, name='group_add'),
    url(r'^group/server_list/(?P<group_id>\d+)/$', group.server_list, name='group_server_list'),
    url(r'^group/edit/(?P<group_id>\d+)/$', group.group_edit, name='group_edit'),
    # url(r'^group/save/$', group.group_save, name='group_save'),
    url(r'^cabinet/$', cabinet.cabinet, name='cabinet'),
    url(r'^cabinet/del/$', cabinet.cabinet_del, name='cabinet_del'),
    url(r'^cabinet/add/$', cabinet.cabinet_add, name='cabinet_add'),
    url(r'^cabinet/server_list/(?P<cabinet_id>\d+)/$', cabinet.server_list, name='cabinet_server_list'),
    url(r'^cabinet/edit/(?P<cabinet_id>\d+)/$', cabinet.cabinet_edit, name='cabinet_edit'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_del, name='idc_del'),
    url(r'^idc/edit/(?P<idc_id>\d+)/$', idc.idc_edit, name='idc_edit'),
    url(r'^idc/cabinetlist/(?P<cabinet_id>\d+)/$', idc.cabinet_list, name='idc_cabinet_list'),
    url(r'^collect', api.collect, name='update_api'),
    url(r'^get/host/', api.get_host, name='get_host'),
    url(r'^get/group/', api.get_group, name='get_group'),
]

appconf/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from cmdb.models import Host


class AuthInfo(models.Model):
    dis_name = models.CharField(u"认证标识", max_length=50, unique=True, blank=False)
    username = models.CharField(u"用户名", max_length=50, blank=True)
    password = models.CharField(u"密码", max_length=50, blank=True)
    private_key = models.CharField(u"密钥", max_length=100, blank=True)
    memo = models.TextField(u"备注信息", max_length=200, blank=True)

    def __unicode__(self):
        return self.dis_name


class AppOwner(models.Model):
    name = models.CharField(u"负责人姓名", max_length=50, unique=True, null=False, blank=False)
    phone = models.CharField(u"负责人手机", max_length=50, null=False, blank=False)
    qq = models.CharField(u"负责人QQ", max_length=100, null=True, blank=True)
    weChat = models.CharField(u"负责人微信", max_length=100, null=True, blank=True)

    def __unicode__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(u"产品线名称", max_length=50, unique=True, null=False, blank=False)
    description = models.CharField(u"产品线描述", max_length=255, null=True, blank=True)
    owner = models.ForeignKey(
        AppOwner, verbose_name=u"产品线负责人",
        null=True, blank=True,
        on_delete=models.SET_NULL
    )

    def __unicode__(self):
        return self.name


class Project(models.Model):
    LANGUAGE_TYPES = (
        ("Java", "Java"),
        ("PHP", "PHP"),
        ("Python", "Python"),
        ("C#", "C#"),
        ("Html", "Html"),
        ("Javascript", "Javascript"),
        ("C/C++", "C/C++"),
        ("Ruby", "Ruby"),
        ("Other", "Other"),
    )

    APP_TYPE = (
        ("Frontend", "Frontend"),
        ("Middleware", "Middleware"),
        ("Backend", "Backend"),
    )

    SERVER_TYPE = (
        ("Tomcat", "Tomcat"),
        ("Weblogic", "Weblogic"),
        ("JETTY", "JETTY"),
        ("Nginx", "Nginx"),
        ("Gunicorn", "Gunicorn"),
        ("Uwsgi", "Uwsgi"),
        ("Apache", "Apache"),
        ("IIS", "IIS"),
    )

    APP_ARCH = (
        ("Django", "Django"),
        ("Flask", "Flask"),
        ("Tornado", "Tornado"),
        ("Dubbo", "Dubbo"),
        ("SSH", "SSH"),
        ("Spring boot", "Spring boot"),
        ("Spring cloud", "Spring cloud"),
        ("Laravel", "Laravel"),
        ("ThinkPHP", "ThinkPHP"),
        ("Phalcon", "Phalcon"),
        ("other", "other"),
    )

    SOURCE_TYPE = (
        ("git", "git"),
        ("svn", "svn"),
    )

    name = models.CharField(u"项目名称", max_length=50, unique=True, null=False, blank=False)
    description = models.CharField(u"项目描述", max_length=255, null=True, blank=True)
    language_type = models.CharField(u"语言类型", choices=LANGUAGE_TYPES, max_length=30, null=True, blank=True)
    app_type = models.CharField(u"程序类型", choices=APP_TYPE, max_length=30, null=True, blank=True)
    server_type = models.CharField(u"服务器类型", choices=SERVER_TYPE, max_length=30, null=True, blank=True)
    app_arch = models.CharField(u"程序框架", choices=APP_ARCH, max_length=30, null=True, blank=True)
    source_type = models.CharField(max_length=255, choices=SOURCE_TYPE, verbose_name=u"源类型", blank=True)
    source_address = models.CharField(max_length=255, verbose_name=u"源地址", null=True, blank=True)
    appPath = models.CharField(u"程序部署路径", max_length=255, null=True, blank=True)
    configPath = models.CharField(u"配置文件路径", max_length=255, null=True, blank=True)
    product = models.ForeignKey(
            Product,
            null=True,
            blank=True,
            on_delete=models.SET_NULL,
            verbose_name=u"所属产品线"
    )
    owner = models.ForeignKey(
            AppOwner,
            null=True,
            blank=True,
            on_delete=models.SET_NULL,
            verbose_name=u"项目负责人"
    )
    serverList = models.ManyToManyField(
            Host,
            blank=True,
            verbose_name=u"所在服务器"
    )

    def __unicode__(self):
        return self.name

appconf/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms.widgets import *
from .models import Product, Project, AppOwner, AuthInfo


class AuthInfoForm(forms.ModelForm):

    class Meta:
        model = AuthInfo
        exclude = ("id",)
        widgets = {
            'dis_name': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'username': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'password': TextInput(attrs={'class': 'form-control', 'type': 'password', 'style': 'width:450px'}),
            'private_key': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'memo': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
        }


class AppOwnerForm(forms.ModelForm):

    class Meta:
        model = AppOwner
        exclude = ("id",)
        widgets = {
            'name': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
            'phone': TextInput(attrs={'class': 'form-control','style': 'width:450px'}),
            'qq': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
            'weChat': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
        }


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ("id",)
        widgets = {
            'name': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
            'description': Textarea(attrs={'class': 'form-control','style': 'width:450px; height:100px'}),
            'owner': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
        }


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        exclude = ("id",)

        widgets = {
            'name': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
            'description': Textarea(attrs={'class': 'form-control','style': 'width:450px; height:100px'}),
            'language_type': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'app_type': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'server_type': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'app_arch': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'appPath': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
            'source_type': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'source_address': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
            'configPath': TextInput(attrs={'class': 'form-control','style': 'width:450px;'}),
            'product': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'owner': Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'serverList': forms.SelectMultiple(attrs={'class': 'form-control', 'size':'10', 'multiple': 'multiple'}),
        }

appconf/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

templates/appconf/appconf-header.html
<header class="main-header">

    <!-- Logo -->
    <a href="{% url 'index' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>AST</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>AdminSet</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li style="font-size: medium" id="product_list"><a href="{% url 'product_list' %}"><b>产品线管理</b></a></li>
            <li style="font-size: medium" id="project_list"><a href="{% url 'project_list' %}"><b>项目管理</b></a></li>
            <li style="font-size: medium" id="appowner_list"><a href="{% url 'appowner_list' %}"><b>负责人管理</b></a></li>
            <li style="font-size: medium" id="authinfo_list"><a href="{% url 'authinfo_list' %}"><b>认证管理</b></a></li>

          </ul>
        </div>
      <!-- Navbar Right Menu -->
      {% include 'navbar-custom-menu.html' %}
    </nav>
  </header>

templates/appconf/appowner_add_edit.html
{% extends 'base.html' %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
{% endblock %}
{% block content %}

<script>
        window.onload=init;
        function init() {
            var box = document.getElementById("appconf");
            box.className="active";
            var box = document.getElementById("appowner_list");
            box.className="active";
        }
</script>

{% include 'appconf/appowner_base.html' %}

{% endblock %}

templates/appconf/appowner_add_edit_mini.html
{% include 'link_css.html' %}
{% include 'head_script.html' %}
<script src="/static/layer/layer.js"></script>

{% include 'appconf/appowner_base.html' %}

{#回传参数至父层#}
<script type="text/javascript">
        var index = parent.layer.getFrameIndex(window.name);
        var status = {{ status }};
        if(status> 0){
            var app_owner_id = "{{ owner_id }}";
            var app_owner_name = "{{ owner_name }}";
            parent.$("#new_owner_id").val(app_owner_id);
            parent.$("#new_owner_name").val(app_owner_name);
            parent.$("#handle_status").val(status);
            parent.layer.close(index);
        }

</script>

templates/appconf/appowner_base.html
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">
    <div id="dialog">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
        {% if appowner_id %}
            <form action="{% url 'appowner_edit' appowner_id %}" method="post">
        {% else %}
            {% if page_type == "whole" %}
                <form action="{% url 'appowner_add' %}" method="post">
            {% else %}
                <form action="{% url 'appowner_add_mini' %}" method="post">
            {% endif %}
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
        {% if page_type == "whole" %}
            <a href="{% url 'appowner_list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
        {% endif %}
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i> 请勿重复添加条目
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </div>
    </section>
  </div>

templates/appconf/appowner_list.html
{% extends 'base.html' %}
{% load mytags %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
    <script src="/static/js/base.js"></script>
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.css"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("appconf");
            box.className="active";
            var box = document.getElementById("appowner_list");
            box.className="active";
        }
    </script>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
        <form action="" method="post" id="appowner_form">
                {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="col-sm-2" style="padding-left: 0">
						 <a href="{% url 'appowner_add' %}"><li class="btn btn-success" ><b>添加负责人</b></li></a>
                  </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                  <table class="table table-striped table-bordered" id="appOwnerform">
                      <thead>
                        <tr>
                            <th>
                                <input id="checkall" type="checkbox" class="i-checks" name="checkall" value="checkall" data-editable='false' onclick="check_all('appowner_form')">
                            </th>
                            <th>负责人姓名</th>
                            <th>负责人手机</th>
                            <th>负责人QQ</th>
                            <th>负责人微信</th>
                            <th>操作</th>
                        </tr>
                      </thead>
                            <tbody>
                            {% for owner in all_app_owner %}
                                <tr class="even gradeX">
                                    <td><input type="checkbox" id="id" class="i-checks" value="{{ owner.id }}" name="id" /></td>
                                    <td>{{ owner.name }} </td>
                                    <td>{{ owner.phone }} </td>
                                    <td>{{ owner.qq }} </td>
                                    <td>{{ owner.weChat }} </td>
                                    <td>
                                        <a href="{% url "appowner_edit" owner.id %}"><span class="btn btn-sm btn-info">编辑</span></a>
                                        <a href="{% url "appowner_del"%}?id={{ owner.id }}" onclick="return confirm('确认删除负责人吗？')"><span class="btn btn-sm btn-danger ">删除</span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                  </table>
                  <div class="btn-group">
                      <input type="button" id="appowner_del" class="btn btn-danger"   name="del_button" value="删除负责人"/>
                  </div>
                </div>
            </div>
        </form>
    </section>

</div>
<script>
  $(function () {
    $('#appOwnerform').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": true
    });
  });
</script>

<script>
    $('#appowner_del').click(function () {
        var appowner_id_all = getIDall();
        if (appowner_id_all == ''){
            alert("请至少选择一行!");
            return false;
        }
        if (confirm("确定删除?")) {
            $.ajax({
                type: "post",
                data: {appowner_id_all: appowner_id_all,csrfmiddlewaretoken: '{{ csrf_token }}'},
                url: "{% url 'appowner_del' %}",
                success: function () {
                    parent.location.reload();
                }
            });
        }
    });
</script>

{% endblock %}

templates/appconf/authinfo_add_edit.html
{% extends 'base.html' %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
{% endblock %}
{% block content %}

<script>
        window.onload=init;
        function init() {
            var box = document.getElementById("appconf");
            box.className="active";
            var box = document.getElementById("authinfo_list");
            box.className="active";
        }
</script>

{% include 'appconf/authinfo_base.html' %}

{% endblock %}

templates/appconf/authinfo_add_edit_mini.html
{% include 'link_css.html' %}
{% include 'head_script.html' %}
<script src="/static/layer/layer.js"></script>

{% include 'appconf/authinfo_base.html' %}

{#回传参数至父层#}
<script type="text/javascript">
        var index = parent.layer.getFrameIndex(window.name);
        var status = {{ status }};
        if(status> 0){
            var auth_info_id = "{{ auth_id }}";
            var auth_info_name = "{{ auth_name }}";
            parent.$("#new_auth_id").val(auth_info_id);
            parent.$("#new_auth_name").val(auth_info_name);
            parent.$("#handle_status").val(status);
            parent.layer.close(index);
        }

</script>

templates/appconf/authinfo_base.html
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">
    <div id="dialog">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
        {% if authinfo_id %}
            <form action="{% url 'authinfo_edit' authinfo_id %}" method="post">
        {% else %}
            {% if page_type == "whole" %}
                <form action="{% url 'authinfo_add' %}" method="post">
            {% else %}
                <form action="{% url 'authinfo_add_mini' %}" method="post">
            {% endif %}
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
        {% if page_type == "whole" %}
            <a href="{% url 'authinfo_list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
        {% endif %}
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i> 请勿重复添加条目
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </div>
    </section>
  </div>

templates/appconf/authinfo_list.html
{% extends 'base.html' %}
{% load mytags %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
    <script src="/static/js/base.js"></script>
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.css"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("appconf");
            box.className="active";
            var box = document.getElementById("authinfo_list");
            box.className="active";
        }
    </script>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
        <form action="" method="post" id="authinfo_form">
                {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="col-sm-2" style="padding-left: 0">
						 <a href="{% url 'authinfo_add' %}"><li class="btn btn-success" ><b>添加认证</b></li></a>
                  </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                  <table class="table table-striped table-bordered" id="authInfoform">
                      <thead>
                        <tr>
                            <th>
                                <input id="checkall" type="checkbox" class="i-checks" name="checkall" value="checkall" data-editable='false' onclick="check_all('authinfo_form')">
                            </th>
                            <th>用户名</th>
                            <th>备注</th>
                        </tr>
                      </thead>
                            <tbody>
                            {% for auth in all_authinfo %}
                                <tr class="even gradeX">
                                    <td><input type="checkbox" id="id" class="i-checks" value="{{ auth.id }}" name="id" /></td>
                                    <td>{{ auth.dis_name }} </td>
                                    <td>{{ auth.memo }} </td>
                                    <td>
                                        <a href="{% url "authinfo_edit" auth.id %}"><span class="btn btn-sm btn-info">编辑</span></a>
                                        <a href="{% url "authinfo_del"%}?id={{ auth.id }}" onclick="return confirm('确认删除认证？')"><span class="btn btn-sm btn-danger ">删除</span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                  </table>
                  <div class="btn-group">
                      <input type="button" id="authinfo_del" class="btn btn-danger"   name="del_button" value="删除认证"/>
                  </div>
                </div>
            </div>
        </form>
    </section>

</div>
<script>
  $(function () {
    $('#authInfoform').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": true
    });
  });
</script>

<script>
    $('#authinfo_del').click(function () {
        var authinfo_id_all = getIDall();
        if (authinfo_id_all == ''){
            alert("请至少选择一行!");
            return false;
        }
        if (confirm("确定删除?")) {
            $.ajax({
                type: "post",
                data: {authinfo_id_all: authinfo_id_all,csrfmiddlewaretoken: '{{ csrf_token }}'},
                url: "{% url 'authinfo_del' %}",
                success: function () {
                    parent.location.reload();
                }
            });
        }
    });
</script>

{% endblock %}

templates/appconf/product_base.html
{% extends 'base.html' %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("appconf");
            box.className="active";
            var box = document.getElementById("product_list");
            box.className="active";
        }
    </script>

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
        {% if product_id %}
            <form action="{% url 'product_edit' product_id %}" method="post">
        {% else %}
            <form action="{% url 'product_add' %}" method="post">
        {% endif %}
        {% csrf_token %}
        <!--{{ form.as_p }}-->
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {% if field.html_name == "owner" %}
                    {{ field.label_tag }} {{ field }}
                    <a href="#" onclick="return popWin()"><li class="btn btn-success" ><b>添加负责人</b></li></a>
                {% else %}
                    {{ field.label_tag }} {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        <br>
        <br>
        <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'product_list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i> 请勿重复添加条目
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </section>
    {#用于接收appowner_base.html中layui子层的传值#}
    <input id="handle_status" value="" hidden="hidden">
    <input id="new_owner_id" value="" hidden="hidden">
    <input id="new_owner_name" value="" hidden="hidden">
  </div>
<script>
function popWin(){
  layer.open({
      type: 2,
      title: '项目列表',
      area: ['700px', '500px'],
      shadeClose: true, //点击遮罩关闭
      content: ['/appconf/appowner/add/mini/'],
      end:function(){
            var handle_status = $("#handle_status").val();
            if ( handle_status == '1' ) {
                layer.msg('添加成功！',{
                    icon: 1,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){
                    var new_owner_id = $("#new_owner_id").val();
                    var new_owner_name = $("#new_owner_name").val();
                    $('#id_owner').append("<option value="+new_owner_id+" selected='selected'>"+new_owner_name+"</option>");
                });
            } else if ( handle_status == '2' ) {
                layer.msg('添加失败！',{
                    icon: 2,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){

                });
            }
      }
  });
}
</script>
{% endblock %}