adminset/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cmdb/', include('cmdb.urls')),
    url(r'^navi/', include('navi.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('setup.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^appconf/', include('appconf.urls')),
    url(r'^delivery/', include('delivery.urls')),
]

cmdb/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from cmdb import api, idc, asset, group, cabinet


urlpatterns = [
    url(r'asset/$', asset.asset, name='cmdb'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_del, name='asset_del'),
    url(r'^asset/edit/(?P<ids>\d+)/$', asset.asset_edit, name='asset_edit'),
    url(r'^asset/detail/(?P<ids>\d+)/$', asset.server_detail, name='server_detail'),
    # url(r'^asset/save/$', asset.asset_save, name='asset_save'),
    url(r'^group/$', group.group, name='group'),
    url(r'^group/del/$', group.group_del, name='group_del'),
    url(r'^group/add/$', group.group_add, name='group_add'),
    url(r'^group/server_list/(?P<group_id>\d+)/$', group.server_list, name='group_server_list'),
    url(r'^group/edit/(?P<group_id>\d+)/$', group.group_edit, name='group_edit'),
    # url(r'^group/save/$', group.group_save, name='group_save'),
    url(r'^cabinet/$', cabinet.cabinet, name='cabinet'),
    url(r'^cabinet/del/$', cabinet.cabinet_del, name='cabinet_del'),
    url(r'^cabinet/add/$', cabinet.cabinet_add, name='cabinet_add'),
    url(r'^cabinet/server_list/(?P<cabinet_id>\d+)/$', cabinet.server_list, name='cabinet_server_list'),
    url(r'^cabinet/edit/(?P<cabinet_id>\d+)/$', cabinet.cabinet_edit, name='cabinet_edit'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_del, name='idc_del'),
    url(r'^idc/edit/(?P<idc_id>\d+)/$', idc.idc_edit, name='idc_edit'),
    url(r'^idc/cabinetlist/(?P<cabinet_id>\d+)/$', idc.cabinet_list, name='idc_cabinet_list'),
    url(r'^collect', api.collect, name='update_api'),
    url(r'^get/host/', api.get_host, name='get_host'),
    url(r'^get/group/', api.get_group, name='get_group'),
]

delivery/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
import delivery
import tasks
urlpatterns = [
    url(r'^$', delivery.delivery_list, name='delivery'),
    url(r'^add/$', delivery.delivery_add, name='delivery_add'),
    url(r'^ist/$', delivery.delivery_list, name='delivery_list'),
    url(r'^status/(?P<project_id>\d+)/$', delivery.status, name='delivery_status'),
    url(r'^edit/(?P<project_id>\d+)/$', delivery.delivery_edit, name='delivery_edit'),
    url(r'^log/(?P<project_id>\d+)/$', delivery.log, name='delivery_log'),
    url(r'^log2/(?P<project_id>\d+)/$', delivery.log2, name='delivery_log2'),
    url(r'^deploy/(?P<project_id>\d+)/$', delivery.delivery_deploy, name='delivery_deploy'),
    url(r'^taskstop/(?P<project_id>\d+)/$', delivery.task_stop, name='delivery_taskstop'),
    url(r'^delete/$', delivery.delivery_del, name='delivery_del'),
]

delivery/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from appconf.models import Project, AuthInfo
# Create your models here.
DEPLOY_POLICY = (
    ("Direct", "Direct"),
    # ("BlueGreen", "BlueGreen"),
)


class Delivery(models.Model):
    job_name = models.OneToOneField(Project, verbose_name=u"项目名")
    description = models.CharField(max_length=255, verbose_name=u"项目描述", null=True, blank=True)
    deploy_policy = models.CharField(max_length=255, choices=DEPLOY_POLICY, verbose_name=u"部署策略")
    version = models.CharField(max_length=255, verbose_name=u"版本信息", blank=True)
    build_clean = models.BooleanField(verbose_name=u"清理构建", default=False)
    shell = models.CharField(max_length=255, verbose_name=u"shell", blank=True)
    shell_position = models.BooleanField(verbose_name=u"本地执行", default=False)
    status = models.BooleanField(verbose_name=u"部署状态", default=False)
    deploy_num = models.IntegerField(verbose_name=u"部署次数", default=0)
    bar_data = models.IntegerField(default=0)
    auth = models.ForeignKey(
        AuthInfo, verbose_name=u"认证信息",
        null=True, blank=True,
        on_delete=models.SET_NULL
    )

    def __unicode__(self):
        return self.job_name

delivery/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.forms import widgets
from models import Delivery


class DeliveryFrom(forms.ModelForm):

    class Meta:
        model = Delivery
        exclude = ("id", "bar_data", "status")

        widgets = {
            'job_name': widgets.Select(attrs={'class': 'form-control','style': 'width:450px;'}),
            'deploy_num': widgets.TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', "readonly": "readonly"}),
            'version': widgets.TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'description': widgets.Textarea(attrs={'class': 'form-control', 'style': 'width:450px; height:100px'}),
            'deploy_policy': widgets.Select(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'shell': widgets.Textarea(attrs={'class': 'form-control', 'style': 'width:450px; height:100px'}),
            'auth': widgets.Select(attrs={'class': 'form-control','style': 'width:450px;'}),

        }

delivery/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.views.generic.base import TemplateView
from django.shortcuts import render
from models import Delivery


def index(request):
    temp_name = "delivery/delivery-header.html"
    projects = Delivery.objects.all()
    return render(request, "delivery/index.html", locals())

templates/delivery/delivery-header.html
<header class="main-header">

    <!-- Logo -->
    <a href="{% url 'index' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>AST</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>AdminSet</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div>
      <!-- Navbar Right Menu -->
      {% include 'navbar-custom-menu.html' %}
    </nav>
  </header>

templates/delivery/delivery_base.html
{% extends 'base.html' %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
    <script src="/static/js/jquery.bootstrap-duallistbox.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-duallistbox.css">
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("delivery");
            box.className="active";
            var box = document.getElementById("delivery_list");
            box.className="active";
        }
    </script>

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
        {% if project_id %}
            <form action="{% url 'delivery_edit' project_id %}" method="post">
        {% else %}
            <form action="{% url 'delivery_add' %}" method="post">
        {% endif %}
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {% if field.html_name == "auth" %}
                    {{ field.label_tag }} {{ field }}
                    <a href="#" onclick="return popWin()"><li class="btn btn-success" ><b>添加认证</b></li></a>
                {% else %}
                    {{ field.label_tag }} {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        <p></p>
        <input type="submit" class="btn btn-primary" style="width: 60pt" value="保存">&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'delivery_list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i> 请勿重复添加条目
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </section>
    {#用于接收appowner_base.html中layui子层的传值#}
    <input id="handle_status" value="" hidden="hidden">
    <input id="new_auth_id" value="" hidden="hidden">
    <input id="new_auth_name" value="" hidden="hidden">
  </div>
{#    <script>#}
{#        var demo1 = $('select[name="serverList"]').bootstrapDualListbox({#}
{#              nonSelectedListLabel: '可选择服务器',#}
{#              selectedListLabel: '已选择服务器',#}
{#              preserveSelectionOnMove: 'moved',#}
{#              moveOnSelect: false,#}
{#        });#}
{#    </script>#}
<script>
function popWin(){
  layer.open({
      type: 2,
      title: '项目列表',
      area: ['700px', '500px'],
      shadeClose: true, //点击遮罩关闭
      content: ['/appconf/authinfo/add/mini/'],
      end:function(){
            var handle_status = $("#handle_status").val();
            if ( handle_status == '1' ) {
                layer.msg('添加成功！',{
                    icon: 1,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){
                    var new_auth_id = $("#new_auth_id").val();
                    var new_auth_name = $("#new_auth_name").val();
                    $('#id_auth').append("<option value="+new_auth_id+" selected='selected'>"+new_auth_name+"</option>");
                });
            } else if ( handle_status == '2' ) {
                layer.msg('添加失败！',{
                    icon: 2,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){

                });
            }
      }
  });
}
</script>
{% endblock %}

templates/delivery/delivery_list.html
{% extends 'base.html' %}
{% load mytags %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
    <script src="/static/js/base.js"></script>
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.css"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("delivery");
            box.className="active";
            var box = document.getElementById("delivery_list");
            box.className="active";
        }
    </script>
<style type="text/css">
    #progress_bar
    {
        width:132px;
        border: solid 1px;
        background-color: aliceblue;
        height:17px;
    }
</style>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
        <form action="" method="post" id="project_form">
                {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="col-sm-2" style="padding-left: 0">
						 <a href="{% url 'delivery_add' %}"><li class="btn btn-success" ><b>添加项目</b></li></a>
                  </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                  <table class="table table-striped table-bordered" id="projectform">
                      <thead>
                        <tr>
                            <th>
                                <input id="checkall" type="checkbox" class="i-checks" name="checkall" value="checkall" data-editable='false' onclick="check_all('project_form')">
                            </th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Progress</th>
                            <th>Policy</th>
                            <th>Action</th>
                        </tr>
                      </thead>
                            <tbody>
                            {% for project in all_project %}
                                <tr class="even gradeX">
                                    <td><input type="checkbox" id="id" class="i-checks" value="{{ project.id }}" name="id" /></td>
                                    <td>{{ project.job_name }} </td>
                                    <td>
                                            <i class="fa fa-circle" aria-hidden="true" style="color:#2D93CA;"></i>
                                    </td>
                                    <td>
                                    {% if project.status == False %}
                                        <div id="progress_bar_{{ project.job_name.id }}" style="display:none;width:132px;border: solid 1px;background-color: aliceblue;height:17px;">
                                            <div id="pb_{{ project.job_name.id }}" style="background-color: deepskyblue;height:15px; width: 0;"></div>
                                        </div>
                                    {% else %}
                                        <div id="progress_bar_{{ project.job_name.id }}" style="display:block;width:132px;border: solid 1px;background-color: aliceblue;height:17px;">
                                            <div id="pb_{{ project.job_name.id }}" style="background-color: deepskyblue;height:15px; width: 0;"></div>
                                        </div>
                                    {% endif %}

                                    </td>
                                    <td>{{ project.deploy_policy }} </td>
                                    <td>
                                        <a href="#"><li onclick="return deploy(this.value);" class="btn btn-sm btn-default" value="{{ project.job_name_id }}">部署</li></a>
                                        <a href="#"><li style="list-style-type:none" class="btn btn-sm btn-default" onclick="return tanchu(this.value)" value="{{ project.job_name_id  }}">日志</li></a>
                                        <a href="{% url "delivery_edit" project.id %}"><span class="btn btn-sm btn-default">编辑</span></a>
                                        <a href="#"><li onclick="return taskstop(this.value);" class="btn btn-sm btn-default" value="{{ project.job_name_id }}">清理</li></a>
                                        <a href="{% url "delivery_del"%}?project_id={{ project.id }}" onclick="return confirm('确认删除项目吗？')"><span class="btn btn-sm btn-danger ">删除</span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                  </table>
                  <div class="btn-group">
                      <input type="button" id="project_del" class="btn btn-danger"   name="del_button" value="删除项目"/>
                  </div>
                </div>
            </div>
        </form>
    </section>

</div>
<script>
  $(function () {
    $('#projectform').DataTable({
        "aLengthMenu":[5,10],
        "paging": true,
        "lengthChange": true,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": true
    });
  });
</script>

<script>
    $('#project_del').click(function () {
        var project_id_all = getIDall();
        if (project_id_all == ''){
            alert("请至少选择一行!");
            return false;
        }
        if (confirm("确定删除?")) {
            $.ajax({
                type: "post",
                data: {project_id_all: project_id_all,csrfmiddlewaretoken: '{{ csrf_token }}'},
                url: "{% url 'delivery_del' %}",
                success: function () {
                    parent.location.reload();
                }
            });
        }
    });
</script>
<script>
function tanchu(n){
    layer.open({
    type: 2,
    title: 'Deploy Log View',
    closeBtn: 1,
    area: ['600px', '400px'],
    shadeClose: true, //点击遮罩关闭
    content: ['/delivery/log/' + n]
  });
}
</script>

<script>
function deploy(args) {
    if (confirm("确定部署？")) {
        var pb = document.getElementById("progress_bar_"+args);
        pb.style.display = "block";
        $.get("/delivery/deploy/"+args+"/",function(data,status){
        });
    }
}
function taskstop(args) {
    if (confirm("确定清理任务状态？")) {
        var pb = document.getElementById("progress_bar_"+args);
        pb.style.display = "none";
        $.get("/delivery/taskstop/"+args+"/",function(data,status){
        });
    }
}
</script>
<script>
    var v1 = window.setInterval("status()",3000);

    function status() {
        {% for project in all_project %}
            $.get("/delivery/status/{{ project.job_name_id }}/",function(data){
                var ret = JSON.parse(data);
                var width = parseInt(ret.bar_data);
                var progress_bar = document.getElementById("pb_{{ project.job_name.id }}");
                progress_bar.style.width = width+"px";
            });
        {% endfor %}
    }
</script>

{% endblock %}

templates/delivery/results.html
{#{% load mytags %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'link_css.html' %}
    {% include 'head_script.html' %}
</head>
<body>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">

      <!-- Default box -->
      <div class="box">

        <div class="box-body">
{#        {% for d in line %}#}
{#        <p>{{ d|res_splict|safe }}</p><br>#}
{#        {% endfor %}#}
{#        {% if line %}#}
{#            {% for d in line %}#}
{#            {{ d }}<br>#}
{#            {% endfor %}#}
{#        {% else %}#}
{#            <i class="fa fa-spinner fa-pulse fa-2x fa-fw"></i>#}
{#            <span class="sr-only">Loading...</span>#}
{#        {% endif %}#}
        <div id="log_ret">
{#            {% if project.status == False %}#}
        </div>
        <div id="loading">
            <i class="fa fa-spinner fa-pulse fa-2x fa-fw"></i>
            <span class="sr-only">Loading...</span>
{#            {% endif %}#}
{#            {% if project.status == True %}#}
{#                <div id="loading" style="display: block">#}
{#                    <i class="fa fa-spinner fa-pulse fa-2x fa-fw"></i>#}
{#                    <span class="sr-only">Loading...</span>#}
{#                </div>#}
{#            {% endif %}#}
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i>
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
</div>
    </section>

  </div>
</body>
<script>
    var v1 = window.setInterval("status()",2000);

    function status() {
            $.get("/delivery/log2/{{ project_id }}/",function(data){
                document.getElementById("log_ret").innerHTML = data;
                //滚动条自动向下滑动
                $(function(){
                      var h = $(document).height()-$(window).height();
                      $(document).scrollTop(h);
                });
            });

            $.get("/delivery/status/{{ project_id }}/",function(data){
                var ret = JSON.parse(data);
                if (ret.status == false) {
{#                    var obj = document.getElementById("loading");#}
{#                    obj.style.display = "none";#}
                    // stop the v1 timer 停用计时器以减少查询
                    window.clearInterval(v1);
                    //document.getElementById("loading").innerHTML = "<h4>project {{ project.job_name }}  {{ project.deploy_num }}th times deploy finished!</h4>";
                    document.getElementById("loading").innerHTML = "<hr>";

                }

            });
    }
</script>
</html>